### ISSUE TITLE
Define allowed Regions from input video

### ISSUE THREAD

**Issue by felipe-xc** [xc-jp/kowa-Robot_ABD#5]
User should be able to create an allowed Regions image by just giving as input a video with the object of interest moving around

### Main method:
`create_allowed_regions(video: list[np.ndarray], radius: int = 0, dimensions: Optional[list[int]], shape_mask: Optional[np.ndarray]) -> np.ndarray`
This method must
 * create a zeroed array representing initial allowed regions (no allowed region),
 * for each image on the video list:
    * run grasping inference
    * update allowed regions based on the detected objects position
 * Obs: radius, dimensions and shape_mask must be mutually exclusive. We must allow that only one of them is given when the method is called. If 2 or more are given, we must raise ValueError exception
     * Obs: If neither radius, dimensions and shape_mask are given, the method should consider radius = 0 (Only one "pixel" is set)

### Auxiliary methods
`update_allowed_regions(allowed_regions: np.ndarray, position: tuple[int, int], radius: int = 0, dimensions: Optional[list[int]] = None, shape_mask: Optional[np.ndarray] = None, angle: Optional[float] = None) -> None`
This method must:
 * Given an array representing the allowed regions, set to 1 its position given by the indices related to `position`. Besides the the position itself, the method must set as 1:
    * [If shape_mask is provided] the surroundings of position based on `shape_mask` and `angle`
    * [Else, if dimensions is provided] the surroundings of position based on `shape_mask` and `angle`
    * [Else, if radius>0] : the surroundings of position based on the radius
* Obs: If angle is not provided and dimensions or shape_mask are provided, we must raise ValueError exception

### Sub-Tasks
 - [x] #6
 - [x] Extend methods to cover `radius > 0`
 - [ ] Extend methods to cover `dimensions != None`
 - [ ] Extend methods to cover `shape_mask != None`

### Open Project Related Issue
OP#444
https://kowaaisolutions.openproject.com/projects/2dpicking-based-abd/work_packages/444
